apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: blackbox-exporter
    io.cattle.field/appId: cluster-monitoring
    release: cluster-monitoring
    source: rancher-monitoring
  name: blackbox-exporter
  namespace: cattle-prometheus
spec:
  endpoints:
    - interval: 30s
      params:
        module:
          - http_2xx
        target:
          - https://www.rancher.com/
      path: "/probe"
      targetPort: metrics
      relabelings:
        - sourceLabels:
            - __param_target
          targetLabel: target
        - sourceLabels:
            - __param_module
          targetLabel: module
  namespaceSelector:
    matchNames:
      - cattle-prometheus
  selector:
    matchLabels:
      app: blackbox-exporter
