apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: example-app
  namespace: cattle-prometheus
  labels:
    io.cattle.field/appId: cluster-monitoring
    release: cluster-monitoring
    source: rancher-monitoring
spec:
  namespaceSelector:
    matchNames:
      - awx-tower
  selector:
    matchLabels:
      app: awx-tower
  endpoints:
  - port: metrics
    path: /api/v2/metrics
    bearerTokenSecret:
      name: awx-bearer-token
      key: token
