apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    io.cattle.field/appId: cluster-monitoring
    release: cluster-monitoring
    source: rancher-monitoring
  name: mysql-operator
  namespace: cattle-prometheus
spec:
  endpoints:
  - interval: 10s
    path: /metrics
    port: prometheus
    scrapeTimeout: 3s
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app.kubernetes.io/managed-by: mysql.presslabs.org
      app.kubernetes.io/name: mysql
