apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mysql-operator
  namespace: default
spec:
  endpoints:
  - interval: 10s
    path: /metrics
    port: prometheus
    scrapeTimeout: 3s
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app.kubernetes.io/managed-by: mysql.presslabs.org
      app.kubernetes.io/name: mysql
